language: objective-c
cache: cocoapods
podfile: ZZFLEXDemo/Podfile
osx_image: xcode10.1
xcode_project: ZZFLEXDemo/ZZFLEXDemo.xcworkspace
xcode_scheme: ZZFLEXDemo

branches:
  only:
    - master

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

script:
    - set -o pipefail
    - xcodebuild -workspace ZZFLEXDemo/ZZFLEXDemo.xcworkspace -scheme ZZFLEXDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO